Method index
LuisARodr/array-extension pull request #11
Opened 2019-08-22 19:25 UTC by LuisARodr

This adds the `index(spec)` method functionality to the framework.
Also includes tests for the method.

Description of the method:
>Will return the zero based position in the array of the element that satisfies the specification. The specification can be either an object value or a function. If no element  match the specification then a -1 value will be returned.

2019-08-27 20:59 UTC, gustavostuff requested changes

2019-08-27 20:59 UTC, gustavostuff commented on Methods/ArrayExtension.js
> + * Return the zero based position in the array of the element that satisfies
Returns*

2019-08-27 20:59 UTC, gustavostuff commented on Methods/ArrayExtension.js
> + * on search of it, if spec is a fuction then a value is found when the function
function*

2019-08-27 20:59 UTC, gustavostuff commented on test/index.js
> +    it("returns -1 when there's no match for the with an obj spec", function() {
phrasing

2019-08-27 20:59 UTC, gustavostuff commented on test/index.js
> +    it("returns -1 when there's no match for the with a function spec", function() {
same as above

2019-08-27 21:43 UTC, gustavostuff approved these changes

2019-08-29 18:32 UTC, LuisARodr commented
Closing to merge into [dev](https://github.com/LuisARodr/array-extension/tree/dev)

2019-08-29 18:32 UTC, closed without merging