Method pluck
LuisARodr/array-extension pull request #12
Opened 2019-08-22 21:17 UTC by LuisARodr

This adds the `pluck(property)` method functionality to the framework.
Also includes tests for the method.

Description of the method:
>This method will attempt to retrieve the given property of each element in the array and shall return a new array containing that property values.

2019-08-26 22:48 UTC, gustavostuff requested changes

2019-08-26 22:48 UTC, gustavostuff commented on test/pluck.js
> +        const obj1 = {
don't

2019-08-27 15:37 UTC, LuisARodr commented on test/pluck.js
> +        const obj1 = {
Fixed on 37f92be

2019-08-27 21:43 UTC, gustavostuff approved these changes

2019-08-29 18:36 UTC, LuisARodr commented
Closing to merge into [dev](https://github.com/LuisARodr/array-extension/tree/dev)

2019-08-29 18:36 UTC, closed without merging