Method sum
LuisARodr/array-extension pull request #13
Opened 2019-08-22 23:23 UTC by LuisARodr

This adds the sum(spec) method functionality to the framework.
Also includes tests for the method.

Description of the method:
>Will return the summatory of the result of executing the spec function on each array’s element, if there is not spec function then it will return the summatory of the array’s elements. Note that if you have elements that are not numbers it will concatenate strings.

2019-08-26 21:46 UTC, gustavostuff requested changes

2019-08-26 21:46 UTC, gustavostuff commented on test/sum.js
> +    it("should concatenate strings when there are string on the array and there's no spec", function() {
there are strings* (?)

2019-08-27 15:37 UTC, LuisARodr commented on test/sum.js
> +    it("should concatenate strings when there are string on the array and there's no spec", function() {
Fixed on 6e9f1d6

2019-08-27 21:42 UTC, gustavostuff approved these changes

2019-08-29 18:38 UTC, LuisARodr commented
Closing to merge into [dev](https://github.com/LuisARodr/array-extension/tree/dev)

2019-08-29 18:38 UTC, closed without merging