Method max
LuisARodr/array-extension pull request #14
Opened 2019-08-23 17:28 UTC by LuisARodr

This adds the `max(comparer)` method functionality to the framework.
Also includes tests for the method.

Description of the method:
> This method will find and return the maximum value on the collection, a null value will be returned for empty arrays. If not comparer is specified then it will try to evaluate the array elements as if they are numbers. The comparator should be a function that receives 2 parameters, valueA and valueB and shall return a negative number for valueA < valueB scenario, zero when valueA === valueB and finally a positive number when valueA > valueB.

2019-08-26 21:43 UTC, gustavostuff requested changes

2019-08-26 21:43 UTC, gustavostuff commented on Methods/ArrayExtension.js
> + * param not being present means the comparations will be made as if every value
comparison*

2019-08-26 21:43 UTC, gustavostuff commented on Methods/ArrayExtension.js
> +  */
newline

2019-08-27 15:32 UTC, LuisARodr commented on Methods/ArrayExtension.js
> + * param not being present means the comparations will be made as if every value
Fixed on c9f6e13

2019-08-27 15:32 UTC, LuisARodr commented on Methods/ArrayExtension.js
> +  */
Fixed on c9f6e13

2019-08-27 21:42 UTC, gustavostuff approved these changes

2019-08-29 18:39 UTC, LuisARodr commented
Closing to merge into [dev](https://github.com/LuisARodr/array-extension/tree/dev)

2019-08-29 18:39 UTC, closed without merging