Method min
LuisARodr/array-extension pull request #15
Opened 2019-08-23 17:38 UTC by LuisARodr

This adds the min(comparer) method functionality to the framework.
Also includes tests for the method.

Description of the method:
>This method will find and return the minimum value on the collection, a null value will be returned for empty arrays. If not comparer is specified then it will try to evaluate the array elements as if they are numbers. The comparator should be a function that receives 2 parameters, valueA and valueB and shall return a negative number for valueA < valueB scenario, zero when valueA === valueB and finally a positive number when valueA > valueB.

2019-08-26 21:40 UTC, gustavostuff requested changes

2019-08-26 21:40 UTC, gustavostuff commented on Methods/ArrayExtension.js
> + * param not being present means the comparations will be made as if every value
comparison*

2019-08-26 21:40 UTC, gustavostuff commented on Methods/ArrayExtension.js
> + * @throws {TypeError} - If spec is present and is not a function.
according

2019-08-27 15:43 UTC, LuisARodr commented on Methods/ArrayExtension.js
> + * param not being present means the comparations will be made as if every value
Fixed on a22fd8f

2019-08-27 15:43 UTC, LuisARodr commented on Methods/ArrayExtension.js
> + * @throws {TypeError} - If spec is present and is not a function.
Fixed on a22fd8f

2019-08-27 21:41 UTC, gustavostuff approved these changes

2019-08-29 18:41 UTC, LuisARodr commented
Closing to merge into [dev](https://github.com/LuisARodr/array-extension/tree/dev)

2019-08-29 18:41 UTC, closed without merging